#Estas configuraciones se agregan dependiendo de los servicios remotos que se utilizarán
next:
  datasource:
    tomcat:
      url: jdbc:postgresql://localhost:5432/ejemplo
      username: postgres
      password: postgres

sibamex-soporte:
  ribbon:
    listOfServers: https://sibamex-soporte-nesib.brmdocp.banregio.com:443/
  uri: sibamex-soporte

categoria:
  ribbon:
    listOfServers: http://localhost:8080/
  uri: categoria